=== ssb2920/SEM-5/WEB TECH/SEMVPRACS-master/WT/Codes/xml/games.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="games">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="game">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="developer" type="xs:string"/>
                            <xs:element name="year" type="xs:positiveInteger"/>
                            <xs:element name="price" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="person" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ssb2920/SEM-5/WEB TECH/SEMVPRACS-master/WT/Codes/xml/games.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="games.xsl"?>
<games person="me"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://192.168.64.2/xml/games.xml games.xsd">
    <game>
        <title>Days Gone</title>
        <developer>Sony</developer>
        <year>2018</year>
        <price>2500</price>
    </game>
    <game>
        <title>FIFA 20</title>
        <developer>EA</developer>
        <year>2019</year>
        <price>3999</price>
    </game>
    <game>
        <title>PES eFootball 2020</title>
        <developer>Konami</developer>
        <year>2019</year>
        <price>3500</price>
    </game>
</games>
